### ISSUE TITLE
login and password auto file but I still need to click on the button to submit

### ISSUE THREAD

**Issue by calvindomenico** [vladislavk3/userscript-auto-login#2]
just tried the script, I still need to press the buttons to enter the login and password, that needs to be automatic as well

**Comment by vladislavk3** [comment]
Oh, yeah.
I knew I should only fill the characters and the user click the button.
I will fix it soon.

**Comment by calvindomenico** [comment]
looks like the first 1 is idSIButton9

**Comment by vladislavk3** [comment]
Fixed
